---
# These tasks install nginx as a load balancer
- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Copy nginx configuration
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable nginx to start on boot
  become: yes
  service:
    name: nginx
    enabled: yes

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Reload nginx config
  become: yes
  service:
    name: nginx
    state: reloaded
