---
# These tasks install mariadb
- name: Install mariadb
  become: yes
  apt:
    name: mariadb-server
    state: present

- name: Enable mariadb to start on boot
  become: yes
  service:
    name: mariadb
    enabled: yes

- name: Start mariadb
  become: yes
  service:
    name: mariadb
    state: started

- name: Copy configuration file
  become: yes
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf

- name: Restart mariadb
  become: yes
  service:
    name: mariadb
    state: restarted

- name: Create root mariadb account
  become: yes
  command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}'"
  register: command_result
  failed_when: "'using password: NO' not in command_result.stderr and command_result.stderr"
