---
# These tasks install the dotnet core application

- name: Copy app files to www folder
  become: yes
  copy:
    src: app_publish
    dest: /var/www/{{ www_name }}

- name: Configure and copy app_settings.json file
  become: yes
  template:
    src: appsettings.json.j2
    dest: /var/www/{{ www_name }}/app_publish/appsettings.json

- name: Create kestrel service
  become: yes
  vars:
    dll_name: DataGreenHRApplication.dll
  template:
    src: kestrel.service.j2
    dest: "/etc/systemd/system/{{ service['name'] }}.service"

- name: Enable kestrel service to start on boot
  become: yes
  service:
    name: "{{ service['name'] }}"
    enabled: yes

- name: Restart kestrel service
  become: yes
  service:
    name: "{{ service['name'] }}"
    state: restarted
