---
# These tasks install nginx as a reverse proxy
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable nginx to start on boot
  service:
    name: nginx
    enabled: yes

- name: Start nginx
  service:
    name: nginx
    state: started
